/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PesaChargeMain.java
 *
 * Created on 28 Jul, 2015, 7:36:28 AM
 */

package pesacharge1;



import java.sql.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Manish Gupta
 */
public class PesaChargeMain extends javax.swing.JFrame {

    /** Creates new form PesaChargeMain */
    public PesaChargeMain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rb = new javax.swing.ButtonGroup();
        Rbr = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        TitlePnl = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        TPane1 = new javax.swing.JTabbedPane();
        MobRcPnl = new javax.swing.JPanel();
        SubBtn = new javax.swing.JButton();
        CnBtn = new javax.swing.JButton();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        LoginFBtn = new javax.swing.JButton();
        T1 = new javax.swing.JTextField();
        CB = new javax.swing.JComboBox();
        T2 = new javax.swing.JTextField();
        Rb1 = new javax.swing.JRadioButton();
        Rb2 = new javax.swing.JRadioButton();
        DTHRcPnl = new javax.swing.JPanel();
        MobRcPnl1 = new javax.swing.JPanel();
        SubBtn1 = new javax.swing.JButton();
        CnBtn1 = new javax.swing.JButton();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        LoginFBtn1 = new javax.swing.JButton();
        T3 = new javax.swing.JTextField();
        CB1 = new javax.swing.JComboBox();
        T4 = new javax.swing.JTextField();
        RedressalPnl = new javax.swing.JPanel();
        MobRcPnl2 = new javax.swing.JPanel();
        SubBtn2 = new javax.swing.JButton();
        CnBtn2 = new javax.swing.JButton();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        LoginFBtn2 = new javax.swing.JButton();
        T5 = new javax.swing.JTextField();
        CB2 = new javax.swing.JComboBox();
        T6 = new javax.swing.JTextField();
        Rb3 = new javax.swing.JRadioButton();
        Rb4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        CBD = new javax.swing.JComboBox();
        CBM = new javax.swing.JComboBox();
        CBY = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesa Charge");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitlePnl.setBackground(new java.awt.Color(102, 255, 0));

        Title.setFont(new java.awt.Font("Comic Sans MS", 1, 22));
        Title.setText("Pesa Charge");

        L1.setFont(new java.awt.Font("Comic Sans MS", 1, 22));
        L1.setForeground(new java.awt.Color(255, 0, 51));
        L1.setText("A PayTM Product");

        javax.swing.GroupLayout TitlePnlLayout = new javax.swing.GroupLayout(TitlePnl);
        TitlePnl.setLayout(TitlePnlLayout);
        TitlePnlLayout.setHorizontalGroup(
            TitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        TitlePnlLayout.setVerticalGroup(
            TitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(TitlePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        TPane1.setBackground(new java.awt.Color(255, 204, 51));
        TPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        TPane1.setFont(new java.awt.Font("Tahoma", 1, 14));

        MobRcPnl.setBackground(new java.awt.Color(0, 255, 255));
        MobRcPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mobile Recharge", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        MobRcPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubBtn.setFont(new java.awt.Font("Tahoma", 1, 12));
        SubBtn.setText("Submit");
        SubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubBtnActionPerformed(evt);
            }
        });
        MobRcPnl.add(SubBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        CnBtn.setFont(new java.awt.Font("Tahoma", 1, 12));
        CnBtn.setText("Clear");
        CnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnBtnActionPerformed(evt);
            }
        });
        MobRcPnl.add(CnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        L2.setFont(new java.awt.Font("Tahoma", 1, 12));
        L2.setText("Enter Mobile Number");
        MobRcPnl.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        L3.setFont(new java.awt.Font("Tahoma", 1, 12));
        L3.setText("Select Operator");
        MobRcPnl.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        L4.setFont(new java.awt.Font("Tahoma", 1, 12));
        L4.setText("Amount");
        MobRcPnl.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        L5.setFont(new java.awt.Font("Tahoma", 1, 10));
        L5.setText("(Min Rs. 10)");
        MobRcPnl.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 20));

        LoginFBtn.setFont(new java.awt.Font("Tahoma", 1, 12));
        LoginFBtn.setText("Logout");
        LoginFBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginFBtnActionPerformed(evt);
            }
        });
        MobRcPnl.add(LoginFBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 110, -1));

        T1.setFont(new java.awt.Font("Tahoma", 1, 12));
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        T1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                T1FocusLost(evt);
            }
        });
        MobRcPnl.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 120, -1));

        CB.setFont(new java.awt.Font("Tahoma", 1, 12));
        CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select One)", "Aircel", "Airtel", "BSNL", "Idea", "MTS Telecom", "Tata Docomo", "Tata Indicom", "Uninor", "Videocon", "Virgin", "Vodafone" }));
        MobRcPnl.add(CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));

        T2.setFont(new java.awt.Font("Tahoma", 1, 12));
        T2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                T2FocusLost(evt);
            }
        });
        MobRcPnl.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 120, -1));

        Rb.add(Rb1);
        Rb1.setFont(new java.awt.Font("Tahoma", 1, 12));
        Rb1.setSelected(true);
        Rb1.setText("Topup");
        Rb1.setFocusPainted(false);
        Rb1.setOpaque(false);
        Rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb1ActionPerformed(evt);
            }
        });
        MobRcPnl.add(Rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Rb.add(Rb2);
        Rb2.setFont(new java.awt.Font("Tahoma", 1, 12));
        Rb2.setText("Special Recharge");
        Rb2.setFocusPainted(false);
        Rb2.setOpaque(false);
        Rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb2ActionPerformed(evt);
            }
        });
        MobRcPnl.add(Rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        TPane1.addTab("Mobile Panel", MobRcPnl);

        MobRcPnl1.setBackground(new java.awt.Color(255, 102, 0));
        MobRcPnl1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DTH Recharge", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 204))); // NOI18N
        MobRcPnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubBtn1.setFont(new java.awt.Font("Tahoma", 1, 12));
        SubBtn1.setText("Submit");
        SubBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubBtn1ActionPerformed(evt);
            }
        });
        MobRcPnl1.add(SubBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        CnBtn1.setFont(new java.awt.Font("Tahoma", 1, 12));
        CnBtn1.setText("Clear");
        CnBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnBtn1ActionPerformed(evt);
            }
        });
        MobRcPnl1.add(CnBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        L6.setFont(new java.awt.Font("Tahoma", 1, 12));
        L6.setText("Enter Customer ID");
        MobRcPnl1.add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        L7.setFont(new java.awt.Font("Tahoma", 1, 12));
        L7.setText("Select Operator");
        MobRcPnl1.add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        L8.setFont(new java.awt.Font("Tahoma", 1, 12));
        L8.setText("Amount");
        MobRcPnl1.add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        L9.setFont(new java.awt.Font("Tahoma", 1, 10));
        L9.setText("(Min Rs. 150)");
        MobRcPnl1.add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 20));

        LoginFBtn1.setFont(new java.awt.Font("Tahoma", 1, 12));
        LoginFBtn1.setText("Logout");
        LoginFBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginFBtn1ActionPerformed(evt);
            }
        });
        MobRcPnl1.add(LoginFBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 110, -1));

        T3.setFont(new java.awt.Font("Tahoma", 1, 12));
        MobRcPnl1.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 120, -1));

        CB1.setFont(new java.awt.Font("Tahoma", 1, 12));
        CB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select One)", "Airtel Digital", "dishTV", "Reliance Big TV", "Sun Direct", "Tata Sky", "Videocon d2h" }));
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });
        MobRcPnl1.add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));

        T4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                T4FocusLost(evt);
            }
        });
        MobRcPnl1.add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 120, -1));

        javax.swing.GroupLayout DTHRcPnlLayout = new javax.swing.GroupLayout(DTHRcPnl);
        DTHRcPnl.setLayout(DTHRcPnlLayout);
        DTHRcPnlLayout.setHorizontalGroup(
            DTHRcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
            .addGroup(DTHRcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DTHRcPnlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MobRcPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        DTHRcPnlLayout.setVerticalGroup(
            DTHRcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
            .addGroup(DTHRcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DTHRcPnlLayout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(MobRcPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        TPane1.addTab("  DTH Panel", DTHRcPnl);

        MobRcPnl2.setBackground(new java.awt.Color(255, 0, 204));
        MobRcPnl2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Redressal Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        MobRcPnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubBtn2.setFont(new java.awt.Font("Tahoma", 1, 12));
        SubBtn2.setText("Check");
        SubBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubBtn2ActionPerformed(evt);
            }
        });
        MobRcPnl2.add(SubBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        CnBtn2.setFont(new java.awt.Font("Tahoma", 1, 12));
        CnBtn2.setText("Clear");
        CnBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnBtn2ActionPerformed(evt);
            }
        });
        MobRcPnl2.add(CnBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        L10.setFont(new java.awt.Font("Tahoma", 1, 12));
        L10.setText("Enter Mobile Number");
        MobRcPnl2.add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        L11.setFont(new java.awt.Font("Tahoma", 1, 12));
        L11.setText("Select Operator");
        MobRcPnl2.add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        L12.setFont(new java.awt.Font("Tahoma", 1, 12));
        L12.setText("Amount");
        MobRcPnl2.add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        LoginFBtn2.setFont(new java.awt.Font("Tahoma", 1, 12));
        LoginFBtn2.setText("Logout");
        LoginFBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginFBtn2ActionPerformed(evt);
            }
        });
        MobRcPnl2.add(LoginFBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 110, -1));

        T5.setFont(new java.awt.Font("Tahoma", 1, 12));
        MobRcPnl2.add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 150, -1));

        CB2.setFont(new java.awt.Font("Tahoma", 1, 12));
        CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select One)", "Aircel", "Airtel", "BSNL", "Idea", "MTS Telecom", "Tata Docomo", "Tata Indicom", "Uninor", "Videocon", "Virgin", "Vodafone" }));
        MobRcPnl2.add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 150, -1));

        T6.setFont(new java.awt.Font("Tahoma", 1, 12));
        T6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6ActionPerformed(evt);
            }
        });
        MobRcPnl2.add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, -1));

        Rbr.add(Rb3);
        Rb3.setFont(new java.awt.Font("Tahoma", 1, 12));
        Rb3.setSelected(true);
        Rb3.setText("For Mobile");
        Rb3.setFocusPainted(false);
        Rb3.setOpaque(false);
        Rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb3ActionPerformed(evt);
            }
        });
        MobRcPnl2.add(Rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Rbr.add(Rb4);
        Rb4.setFont(new java.awt.Font("Tahoma", 1, 12));
        Rb4.setText("For DTH");
        Rb4.setFocusPainted(false);
        Rb4.setOpaque(false);
        Rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb4ActionPerformed(evt);
            }
        });
        MobRcPnl2.add(Rb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Recharge Date");
        MobRcPnl2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        CBD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "24", "25", "26", "27", "28", "29", "30", "31" }));
        MobRcPnl2.add(CBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        CBM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        MobRcPnl2.add(CBM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        CBY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YYYY", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        CBY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBYActionPerformed(evt);
            }
        });
        MobRcPnl2.add(CBY, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        javax.swing.GroupLayout RedressalPnlLayout = new javax.swing.GroupLayout(RedressalPnl);
        RedressalPnl.setLayout(RedressalPnlLayout);
        RedressalPnlLayout.setHorizontalGroup(
            RedressalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MobRcPnl2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        RedressalPnlLayout.setVerticalGroup(
            RedressalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MobRcPnl2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );

        TPane1.addTab("  Redressal Panel", RedressalPnl);

        getContentPane().add(TPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 370, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubBtnActionPerformed
        Database obj = new Database();
         obj.connect();
            String mob = T1.getText();
            long mob1 = Long.parseLong(mob);
            String Op = (String) CB.getSelectedItem();
            String Amt = T2.getText();
            int Amt1 = Integer.parseInt(Amt);
            String Type;
            if (Rb1.isSelected()) {
                Type = "Topup";
            } else {
                Type = "Special";
            }
            try{
                String sql = "Insert Into MobRech Values(" + mob1 + ", '" + Op + "'," + Amt1 + ",'" + Type + "', Curdate());";
            obj.connect();
                obj.stmt.executeUpdate(sql);
                {JOptionPane.showMessageDialog(null, "Succesfully Recharged");}
            }
            catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error in Recharge = "+e);}
            // TODO add your handling code here:


        // TODO add your handling code here:
}//GEN-LAST:event_SubBtnActionPerformed

    private void CnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnBtnActionPerformed
T1.setText(null);
T2.setText(null);
CB.setSelectedIndex(0);
Rb.clearSelection();
Rb1.setSelected(true);
        // TODO add your handling code here:
}//GEN-LAST:event_CnBtnActionPerformed

    private void LoginFBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginFBtnActionPerformed
dispose();
 RegForm object = new RegForm();
object.setVisible(true);
object.setDefaultCloseOperation(RegForm.HIDE_ON_CLOSE);
         // TODO add your handling code here:
    }//GEN-LAST:event_LoginFBtnActionPerformed

    private void SubBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubBtn1ActionPerformed
Database obj = new Database();
         obj.connect();
            String dthid = T3.getText();
            long cid = Long.parseLong(dthid);
            String Op = (String) CB1.getSelectedItem();
            String Amt = T4.getText();
            int Amt1 = Integer.parseInt(Amt);
            try{
                String sql = "Insert Into DthRech Values(" + cid + ", '" + Op + "'," + Amt1+", Curdate());";
            obj.connect();
                obj.stmt.executeUpdate(sql);
                {JOptionPane.showMessageDialog(null, "Succesfully Recharged");}
            }
            catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error in Recharge = "+e);}
            // TODO add your handling code here:
    }//GEN-LAST:event_SubBtn1ActionPerformed

    private void CnBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnBtn1ActionPerformed
T3.setText(null);
T4.setText(null);
CB1.setSelectedIndex(0);
// TODO add your handling code here:
    }//GEN-LAST:event_CnBtn1ActionPerformed

    private void LoginFBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginFBtn1ActionPerformed
dispose();
RegForm object = new RegForm();
object.setVisible(true);
object.setDefaultCloseOperation(RegForm.HIDE_ON_CLOSE);
// TODO add your handling code here:
    }//GEN-LAST:event_LoginFBtn1ActionPerformed

    private void SubBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubBtn2ActionPerformed
Database obj = new Database();
obj.connect();
long no = Long.parseLong(T5.getText());
String Oper = (String) CB2.getSelectedItem();
String d = (String) CBD.getSelectedItem();
String m = (String) CBM.getSelectedItem();
String y = (String) CBY.getSelectedItem();
int day = Integer.parseInt(d);
int month = Integer.parseInt(m);
int year = Integer.parseInt(y);
String date  = year+"-"+month+"-"+day;
java.sql.Date dmy = java.sql.Date.valueOf(date);
int Amt = Integer.parseInt(T6.getText());
String bool;
if (Rb3.isSelected()){
try {
    String sql = "Select * from MobRech where Number = "+no+" And Date = '"+dmy+"' And amount ="+Amt+";";
obj.connect();
obj.rs = obj.stmt.executeQuery(sql);
while(obj.rs.next()){
String Opr = obj.rs.getString("Operator");
int a;
a = Opr.length();
if(a>0){
bool = "Succesfull";
JOptionPane.showMessageDialog(null, "Your Recharge for "+Opr+" was "+bool);
}
else{
bool = "Failed";
JOptionPane.showMessageDialog(null, "Your Recharge for "+Opr+" was "+bool);
}
}


            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error in Connectivity = "+e);
            }

}


else {
try {
    String sql = "Select * from DthRech where C_ID = "+no+" And Date = '"+dmy+"' And amount ="+Amt+";";
obj.connect();
obj.rs = obj.stmt.executeQuery(sql);
while(obj.rs.next()){
String Opr = obj.rs.getString("Operator");
int a;
a = Opr.length();
if(a>0){
bool = "Succesfull";
JOptionPane.showMessageDialog(null, "Your Recharge for "+Opr+" was "+bool);
}
else{
bool = "Failed";
JOptionPane.showMessageDialog(null, "Your Recharge for "+Opr+" was "+bool);
}
}


            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error in Connectivity = "+e);
            }

}
    



        // TODO add your handling code here:
    }//GEN-LAST:event_SubBtn2ActionPerformed

    private void CnBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnBtn2ActionPerformed
T5.setText(null);
T6.setText(null);
Rbr.clearSelection();
Rb3.setSelected(true);
L10.setText("Enter Mobile Number");
CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select One)", "Aircel", "Airtel", "BSNL", "Idea", "MTS Telecom", "Tata Docomo", "Tata Indicom", "Uninor", "Videocon", "Virgin", "Vodafone" }));
          // TODO add your handling code here:
    }//GEN-LAST:event_CnBtn2ActionPerformed

    private void LoginFBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginFBtn2ActionPerformed
dispose();
        RegForm object = new RegForm();
object.setVisible(true);
object.setDefaultCloseOperation(RegForm.HIDE_ON_CLOSE);
         // TODO add your handling code here:
    }//GEN-LAST:event_LoginFBtn2ActionPerformed

    private void Rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb4ActionPerformed
L10.setText("Enter Customer ID");
CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select One)", "Airtel Digital", "dishTV", "Reliance Big TV", "Sun Direct", "Tata Sky", "Videocon d2h" }));

                // TODO add your handling code here:
    }//GEN-LAST:event_Rb4ActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB1ActionPerformed

    private void Rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb3ActionPerformed
L10.setText("Enter Mobile Number");
CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select One)", "Aircel", "Airtel", "BSNL", "Idea", "MTS Telecom", "Tata Docomo", "Tata Indicom", "Uninor", "Videocon", "Virgin", "Vodafone" }));

        // TODO add your handling code here:
    }//GEN-LAST:event_Rb3ActionPerformed

    private void T1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T1FocusLost
String txt = T1.getText();
int a = txt.length();
if (a!=10){JOptionPane.showMessageDialog(null, "Invalid Mobile Number");}

        // TODO add your handling code here:
    }//GEN-LAST:event_T1FocusLost

    private void T2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T2FocusLost
String txt = T2.getText();
long a = Long.parseLong(txt);
if (a<10){JOptionPane.showMessageDialog(null, "Invalid Amount Entered");}
        // TODO add your handling code here:
    }//GEN-LAST:event_T2FocusLost

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void T6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T6ActionPerformed

    private void CBYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBYActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CBYActionPerformed

    private void Rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rb1ActionPerformed

    private void Rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rb2ActionPerformed

    private void T4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T4FocusLost
String txt = T4.getText();
long a = Long.parseLong(txt);
if (a<150){JOptionPane.showMessageDialog(null, "Invalid Amount Entered");}
// TODO add your handling code here:
    }//GEN-LAST:event_T4FocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesaChargeMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB;
    private javax.swing.JComboBox CB1;
    private javax.swing.JComboBox CB2;
    private javax.swing.JComboBox CBD;
    private javax.swing.JComboBox CBM;
    private javax.swing.JComboBox CBY;
    private javax.swing.JButton CnBtn;
    private javax.swing.JButton CnBtn1;
    private javax.swing.JButton CnBtn2;
    private javax.swing.JPanel DTHRcPnl;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JButton LoginFBtn;
    private javax.swing.JButton LoginFBtn1;
    private javax.swing.JButton LoginFBtn2;
    private javax.swing.JPanel MobRcPnl;
    private javax.swing.JPanel MobRcPnl1;
    private javax.swing.JPanel MobRcPnl2;
    private javax.swing.ButtonGroup Rb;
    private javax.swing.JRadioButton Rb1;
    private javax.swing.JRadioButton Rb2;
    private javax.swing.JRadioButton Rb3;
    private javax.swing.JRadioButton Rb4;
    private javax.swing.ButtonGroup Rbr;
    private javax.swing.JPanel RedressalPnl;
    private javax.swing.JButton SubBtn;
    private javax.swing.JButton SubBtn1;
    private javax.swing.JButton SubBtn2;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTabbedPane TPane1;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TitlePnl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
