/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegForm.java
 *
 * Created on 26 Jul, 2015, 11:52:48 AM
 */

package pesacharge1;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Manish Gupta
 */
public class RegForm extends javax.swing.JFrame {

    /** Creates new form RegForm */
    public RegForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rb = new javax.swing.ButtonGroup();
        MobRcPnl3 = new javax.swing.JPanel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        SubBtn = new javax.swing.JButton();
        CB = new javax.swing.JComboBox();
        Rb1 = new javax.swing.JRadioButton();
        Rb2 = new javax.swing.JRadioButton();
        L4 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        L5 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        L6 = new javax.swing.JLabel();
        PF1 = new javax.swing.JPasswordField();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        PF2 = new javax.swing.JPasswordField();
        CnBtn1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        TitlePnl = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        TPNReg = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtemaill = new javax.swing.JTextField();
        PwdPff = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Pnl1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmob = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        PwdPf = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        MobRcPnl3.setBackground(new java.awt.Color(51, 255, 0));
        MobRcPnl3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration/Login Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        MobRcPnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L2.setFont(new java.awt.Font("Tahoma", 1, 12));
        L2.setText("Name");
        MobRcPnl3.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        L3.setFont(new java.awt.Font("Tahoma", 1, 12));
        L3.setText("Monthly Income");
        MobRcPnl3.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        T3.setFont(new java.awt.Font("Tahoma", 1, 12));
        MobRcPnl3.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, -1));

        SubBtn.setFont(new java.awt.Font("Tahoma", 1, 12));
        SubBtn.setText("Submit");
        SubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubBtnActionPerformed(evt);
            }
        });
        MobRcPnl3.add(SubBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        CB.setFont(new java.awt.Font("Tahoma", 1, 12));
        CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select One)", "<Rs. 10000", "Rs. 10001 - 25000", "Rs. 25001 - 50000", "Rs. 50001 - 75000", "Rs. 75001 - 1 Lakh", ">Rs. 1 Lakh" }));
        CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBActionPerformed(evt);
            }
        });
        MobRcPnl3.add(CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, -1));

        Rb.add(Rb1);
        Rb1.setFont(new java.awt.Font("Tahoma", 1, 12));
        Rb1.setText("Registered User/ Login");
        Rb1.setFocusable(false);
        Rb1.setOpaque(false);
        Rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb1ActionPerformed(evt);
            }
        });
        MobRcPnl3.add(Rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Rb.add(Rb2);
        Rb2.setFont(new java.awt.Font("Tahoma", 1, 12));
        Rb2.setSelected(true);
        Rb2.setText("New User/ Create Account");
        Rb2.setFocusable(false);
        Rb2.setOpaque(false);
        Rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb2ActionPerformed(evt);
            }
        });
        MobRcPnl3.add(Rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        L4.setFont(new java.awt.Font("Tahoma", 1, 12));
        L4.setText("Mobile Number");
        MobRcPnl3.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        T1.setFont(new java.awt.Font("Tahoma", 1, 12));
        MobRcPnl3.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, -1));

        L5.setFont(new java.awt.Font("Tahoma", 1, 12));
        L5.setText("Email");
        MobRcPnl3.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        T2.setFont(new java.awt.Font("Tahoma", 1, 12));
        MobRcPnl3.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, -1));

        L6.setFont(new java.awt.Font("Tahoma", 1, 12));
        L6.setText("Password");
        MobRcPnl3.add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        PF1.setFont(new java.awt.Font("Tahoma", 1, 12));
        MobRcPnl3.add(PF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, -1));

        L7.setBackground(new java.awt.Color(51, 255, 0));
        L7.setFont(new java.awt.Font("Tahoma", 1, 12));
        L7.setForeground(new java.awt.Color(51, 255, 0));
        L7.setText("Enter USER ID");
        L7.setRequestFocusEnabled(false);
        MobRcPnl3.add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        L8.setBackground(new java.awt.Color(51, 255, 0));
        L8.setFont(new java.awt.Font("Tahoma", 1, 12));
        L8.setForeground(new java.awt.Color(51, 255, 0));
        L8.setText("Enter Password");
        L8.setRequestFocusEnabled(false);
        MobRcPnl3.add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        T4.setFont(new java.awt.Font("Tahoma", 1, 12));
        T4.setEnabled(false);
        T4.setOpaque(false);
        MobRcPnl3.add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 140, -1));

        PF2.setFont(new java.awt.Font("Tahoma", 1, 12));
        PF2.setEnabled(false);
        PF2.setOpaque(false);
        MobRcPnl3.add(PF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, -1));

        CnBtn1.setFont(new java.awt.Font("Tahoma", 1, 12));
        CnBtn1.setText("Clear");
        CnBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnBtn1ActionPerformed(evt);
            }
        });
        MobRcPnl3.add(CnBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        MobRcPnl3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 370, 270));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesa Charge R/L Form");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitlePnl.setBackground(new java.awt.Color(51, 255, 255));

        Title.setFont(new java.awt.Font("Comic Sans MS", 1, 22));
        Title.setText("Pesa Charge");

        L1.setFont(new java.awt.Font("Comic Sans MS", 1, 22));
        L1.setForeground(new java.awt.Color(255, 0, 51));
        L1.setText("A PayTM Product");

        javax.swing.GroupLayout TitlePnlLayout = new javax.swing.GroupLayout(TitlePnl);
        TitlePnl.setLayout(TitlePnlLayout);
        TitlePnlLayout.setHorizontalGroup(
            TitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        TitlePnlLayout.setVerticalGroup(
            TitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(TitlePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        TPNReg.setBackground(new java.awt.Color(255, 204, 51));
        TPNReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Enter Your Email ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Enter Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txtemaill.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtemaill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemaillActionPerformed(evt);
            }
        });
        jPanel2.add(txtemaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 160, -1));

        PwdPff.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel2.add(PwdPff, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesacharge1/84_170x60.jpg"))); // NOI18N
        jLabel7.setLabelFor(this);
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Powered By - ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Presented By - ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesacharge1/logo gw.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 70));

        TPNReg.addTab("Login Here", jPanel2);

        Pnl1.setBackground(new java.awt.Color(51, 255, 51));
        Pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Name");
        Pnl1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Password");
        Pnl1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Email");
        Pnl1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Mobile");
        Pnl1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtmob.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtmob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmobFocusLost(evt);
            }
        });
        Pnl1.add(txtmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, -1));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 12));
        Pnl1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 120, -1));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 12));
        Pnl1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 120, 20));

        PwdPf.setFont(new java.awt.Font("Tahoma", 1, 12));
        Pnl1.add(PwdPf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 120, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Pnl1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Pnl1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Pnl1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        TPNReg.addTab("New User/Register Here", Pnl1);

        getContentPane().add(TPNReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 370, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubBtnActionPerformed
Database obj = new Database();
obj.connect();
String name = T1.getText();
String pwd = new String(PF1.getPassword());
String Email = T3.getText();
int Mobile = Integer.parseInt(T2.getText());
String sql = "Insert Into RegId";




        // TODO add your handling code here:
}//GEN-LAST:event_SubBtnActionPerformed

    private void CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CBActionPerformed

    private void Rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb1ActionPerformed
T1.setVisible(false);
T2.setVisible(false);
T3.setVisible(false);
PF1.setVisible(false);
L2.setVisible(false);
L3.setVisible(false);
L4.setVisible(false);
L5.setVisible(false);
CB.setVisible(false);
L6.setVisible(false);
L7.setVisible(true);
L8.setVisible(true);
T4.setVisible(true);
PF2.setVisible(true);
L7.setEnabled(true);
L8.setEnabled(true);
T4.setEnabled(true);
PF2.setEnabled(true);
L7.setFocusable(true);
L8.setFocusable(true);
T4.setFocusable(true);
PF2.setFocusable(true);
T4.setOpaque(true);
PF2.setOpaque(true);
T4.setEditable(true);
PF2.setEditable(true);
L7.setForeground(Color.BLACK);
L8.setForeground(Color.BLACK);
// TODO add your handling code here:
}//GEN-LAST:event_Rb1ActionPerformed

    private void Rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb2ActionPerformed
T1.setVisible(true);
T2.setVisible(true);
T3.setVisible(true);
PF1.setVisible(true);
L2.setVisible(true);
L3.setVisible(true);
L4.setVisible(true);
L5.setVisible(true);
CB.setVisible(true);
L6.setVisible(true);
L7.setVisible(false);
L8.setVisible(false);
T4.setVisible(false);
PF2.setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_Rb2ActionPerformed

    private void CnBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnBtn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtemaillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemaillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemaillActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Database obj = new Database();
obj.connect();
String name = txtname.getText();
String pwd = new String(PwdPf.getPassword());
String Email = txtemail.getText();
long mob = Long.parseLong(txtmob.getText());

 try {
String sql = "Insert into Reg Values('"+name+"', '"+pwd+"', '"+Email+"', "+mob+");";
            obj.connect();
            obj.stmt.executeUpdate(sql);
             JOptionPane.showMessageDialog(null, "Succesfully Registered");
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Already Exists");

        }




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmobFocusLost
String txt = txtmob.getText();
int a = txt.length();
if (a!=10){JOptionPane.showMessageDialog(null, "Invalid Mobile Number");}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

Database obj = new Database();
obj.connect();
String Id = txtemaill.getText();
String Pass = new String(PwdPff.getPassword());
try{
    String sql = "Select Email, password, Name from Reg Where Email = '"+Id+"';";
    obj.connect();
    obj.rs = obj.stmt.executeQuery(sql);
    while (obj.rs.next()){
    String email = obj.rs.getString("Email");
    String pwd = obj.rs.getString("password");
    String Name = obj.rs.getString("Name");
    if(email.equalsIgnoreCase(Id) && pwd.equalsIgnoreCase(Pass))
    {
    JOptionPane.showMessageDialog(null, "Welcome, "+" "+Name);
    dispose();
    PesaChargeMain objj = new PesaChargeMain();
objj.setVisible(true);
objj.setDefaultCloseOperation(PesaChargeMain.HIDE_ON_CLOSE);
    }
    else{JOptionPane.showMessageDialog(null, "Invalid Credentials");}}
}
 catch(Exception e){
     JOptionPane.showMessageDialog(null, "Invalid Credentials = "+e);
 }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
txtname.setText(null);
PwdPf.setText(null);
txtemail.setText(null);
txtmob.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
txtemaill.setText(null);
PwdPff.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB;
    private javax.swing.JButton CnBtn1;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JPanel MobRcPnl3;
    private javax.swing.JPasswordField PF1;
    private javax.swing.JPasswordField PF2;
    private javax.swing.JPanel Pnl1;
    private javax.swing.JPasswordField PwdPf;
    private javax.swing.JPasswordField PwdPff;
    private javax.swing.ButtonGroup Rb;
    private javax.swing.JRadioButton Rb1;
    private javax.swing.JRadioButton Rb2;
    private javax.swing.JButton SubBtn;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTabbedPane TPNReg;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TitlePnl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemaill;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
